/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiview;

/**
 *
 * @author kacper
 */
public class adminPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanelUI
     */
    public adminPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlManageAccounts = new javax.swing.JPanel();
        lblAccountsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAccounts = new javax.swing.JList<>();
        btnAddNewUser = new javax.swing.JButton();
        btnRemoveSelected = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        pnlProvideFeedback = new javax.swing.JPanel();
        lblDoctorListTitle = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstDoctorList = new javax.swing.JList<>();
        jSeparator7 = new javax.swing.JSeparator();
        lblUserReviewsTitle = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstUserReviews = new javax.swing.JList<>();
        lblSendFeedback = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaFeedback = new javax.swing.JTextArea();
        jSeparator8 = new javax.swing.JSeparator();
        btnSendFeedback = new javax.swing.JButton();

        setBackground(new java.awt.Color(76, 107, 110));

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        pnlManageAccounts.setBackground(new java.awt.Color(143, 174, 177));

        lblAccountsTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAccountsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountsTitle.setText("Accounts:");

        lstAccounts.setBackground(new java.awt.Color(255, 255, 255));
        lstAccounts.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lstAccounts.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(lstAccounts);

        btnAddNewUser.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewUser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddNewUser.setForeground(new java.awt.Color(102, 102, 102));
        btnAddNewUser.setText("Add New User");

        btnRemoveSelected.setBackground(new java.awt.Color(255, 255, 255));
        btnRemoveSelected.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRemoveSelected.setForeground(new java.awt.Color(102, 102, 102));
        btnRemoveSelected.setText("Remove Selected");
        btnRemoveSelected.setToolTipText("");

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlManageAccountsLayout = new javax.swing.GroupLayout(pnlManageAccounts);
        pnlManageAccounts.setLayout(pnlManageAccountsLayout);
        pnlManageAccountsLayout.setHorizontalGroup(
            pnlManageAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageAccountsLayout.createSequentialGroup()
                .addGroup(pnlManageAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageAccountsLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblAccountsTitle))
                    .addGroup(pnlManageAccountsLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(pnlManageAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlManageAccountsLayout.createSequentialGroup()
                                .addComponent(btnRemoveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlManageAccountsLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        pnlManageAccountsLayout.setVerticalGroup(
            pnlManageAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageAccountsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblAccountsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(pnlManageAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewUser)
                    .addComponent(btnRemoveSelected))
                .addGap(109, 109, 109))
        );

        jTabbedPane1.addTab("ManageAccounts", pnlManageAccounts);

        pnlProvideFeedback.setBackground(new java.awt.Color(143, 174, 177));
        pnlProvideFeedback.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblDoctorListTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDoctorListTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorListTitle.setText("Doctor List:");

        lstDoctorList.setBackground(new java.awt.Color(255, 255, 255));
        lstDoctorList.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lstDoctorList.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(lstDoctorList);

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        lblUserReviewsTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUserReviewsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblUserReviewsTitle.setText("User Reviews:");

        lstUserReviews.setBackground(new java.awt.Color(255, 255, 255));
        lstUserReviews.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lstUserReviews.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(lstUserReviews);

        lblSendFeedback.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSendFeedback.setForeground(new java.awt.Color(255, 255, 255));
        lblSendFeedback.setText("Send Feedback:");

        txtaFeedback.setBackground(new java.awt.Color(255, 255, 255));
        txtaFeedback.setColumns(20);
        txtaFeedback.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtaFeedback.setForeground(new java.awt.Color(0, 0, 0));
        txtaFeedback.setRows(5);
        jScrollPane2.setViewportView(txtaFeedback);

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        btnSendFeedback.setBackground(new java.awt.Color(255, 255, 255));
        btnSendFeedback.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSendFeedback.setText("Send Feedback");

        javax.swing.GroupLayout pnlProvideFeedbackLayout = new javax.swing.GroupLayout(pnlProvideFeedback);
        pnlProvideFeedback.setLayout(pnlProvideFeedbackLayout);
        pnlProvideFeedbackLayout.setHorizontalGroup(
            pnlProvideFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProvideFeedbackLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlProvideFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProvideFeedbackLayout.createSequentialGroup()
                        .addGroup(pnlProvideFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDoctorListTitle)
                            .addGroup(pnlProvideFeedbackLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProvideFeedbackLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(pnlProvideFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserReviewsTitle)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProvideFeedbackLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlProvideFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProvideFeedbackLayout.createSequentialGroup()
                                .addComponent(lblSendFeedback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addComponent(btnSendFeedback)
                        .addGap(64, 64, 64))))
        );
        pnlProvideFeedbackLayout.setVerticalGroup(
            pnlProvideFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProvideFeedbackLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblDoctorListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserReviewsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSendFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProvideFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendFeedback))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ProvideFeedback", pnlProvideFeedback);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JButton btnRemoveSelected;
    private javax.swing.JButton btnSendFeedback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAccountsTitle;
    private javax.swing.JLabel lblDoctorListTitle;
    private javax.swing.JLabel lblSendFeedback;
    private javax.swing.JLabel lblUserReviewsTitle;
    private javax.swing.JList<String> lstAccounts;
    private javax.swing.JList<String> lstDoctorList;
    private javax.swing.JList<String> lstUserReviews;
    private javax.swing.JPanel pnlManageAccounts;
    private javax.swing.JPanel pnlProvideFeedback;
    private javax.swing.JTextArea txtaFeedback;
    // End of variables declaration//GEN-END:variables
}
