/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiview;

/**
 *
 * @author kacper
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOverride = new javax.swing.JPanel();
        pnlSettings = new javax.swing.JPanel();
        lblUserSettingsTitle = new javax.swing.JLabel();
        btnLogOff = new javax.swing.JButton();
        btnRequestTermnation = new javax.swing.JButton();
        pnlNotfications = new javax.swing.JPanel();
        lblNotficationsTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaNotfications = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlOverride.setBackground(new java.awt.Color(0, 96, 15));

        javax.swing.GroupLayout pnlOverrideLayout = new javax.swing.GroupLayout(pnlOverride);
        pnlOverride.setLayout(pnlOverrideLayout);
        pnlOverrideLayout.setHorizontalGroup(
            pnlOverrideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pnlOverrideLayout.setVerticalGroup(
            pnlOverrideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlSettings.setBackground(new java.awt.Color(106, 191, 105));
        pnlSettings.setForeground(new java.awt.Color(0, 0, 0));

        lblUserSettingsTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUserSettingsTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblUserSettingsTitle.setText("User Settings:");

        btnLogOff.setBackground(new java.awt.Color(56, 142, 60));
        btnLogOff.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogOff.setForeground(new java.awt.Color(0, 0, 0));
        btnLogOff.setText("Log Off");
        btnLogOff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnLogOff.setBorderPainted(false);

        btnRequestTermnation.setBackground(new java.awt.Color(255, 142, 60));
        btnRequestTermnation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRequestTermnation.setForeground(new java.awt.Color(0, 0, 0));
        btnRequestTermnation.setText("Request Termnation");
        btnRequestTermnation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnRequestTermnation.setBorderPainted(false);

        javax.swing.GroupLayout pnlSettingsLayout = new javax.swing.GroupLayout(pnlSettings);
        pnlSettings.setLayout(pnlSettingsLayout);
        pnlSettingsLayout.setHorizontalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRequestTermnation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSettingsLayout.createSequentialGroup()
                        .addComponent(lblUserSettingsTitle)
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSettingsLayout.setVerticalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserSettingsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOff, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRequestTermnation, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pnlNotfications.setBackground(new java.awt.Color(106, 191, 105));
        pnlNotfications.setForeground(new java.awt.Color(0, 0, 0));

        lblNotficationsTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNotficationsTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblNotficationsTitle.setText("Notfications:");

        txtaNotfications.setEditable(false);
        txtaNotfications.setBackground(new java.awt.Color(255, 255, 255));
        txtaNotfications.setColumns(20);
        txtaNotfications.setForeground(new java.awt.Color(0, 0, 0));
        txtaNotfications.setRows(5);
        txtaNotfications.setFocusable(false);
        jScrollPane2.setViewportView(txtaNotfications);

        btnClear.setBackground(new java.awt.Color(56, 142, 60));
        btnClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnClear.setBorderPainted(false);

        javax.swing.GroupLayout pnlNotficationsLayout = new javax.swing.GroupLayout(pnlNotfications);
        pnlNotfications.setLayout(pnlNotficationsLayout);
        pnlNotficationsLayout.setHorizontalGroup(
            pnlNotficationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotficationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNotficationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlNotficationsLayout.createSequentialGroup()
                        .addComponent(lblNotficationsTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNotficationsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlNotficationsLayout.setVerticalGroup(
            pnlNotficationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotficationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotficationsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOverride, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNotfications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOverride, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlNotfications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogOff;
    private javax.swing.JButton btnRequestTermnation;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNotficationsTitle;
    private javax.swing.JLabel lblUserSettingsTitle;
    private javax.swing.JPanel pnlNotfications;
    private javax.swing.JPanel pnlOverride;
    private javax.swing.JPanel pnlSettings;
    private javax.swing.JTextArea txtaNotfications;
    // End of variables declaration//GEN-END:variables
}
