/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiview;

/**
 *
 * @author kacper
 */
public class perscriptionUI extends javax.swing.JFrame {

    /**
     * Creates new form registerUI
     */
    public perscriptionUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPatientTitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPatientTitleName = new javax.swing.JLabel();
        lblPatientTitleAddress = new javax.swing.JLabel();
        lblPatientTitleSex = new javax.swing.JLabel();
        lblPatientTitleAge = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientAddress = new javax.swing.JLabel();
        lblPatientSex = new javax.swing.JLabel();
        lblPatientAge = new javax.swing.JLabel();
        lblDoctorTitle = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblDoctorTitleName = new javax.swing.JLabel();
        lblDoctorTitleAddress = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        lblDoctorAddress = new javax.swing.JLabel();
        lblNotesTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaNotes = new javax.swing.JTextArea();
        lblMedicineTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(76, 107, 110));
        pnlBackground.setForeground(new java.awt.Color(76, 107, 110));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("Perscription View");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        lblPatientTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPatientTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientTitle.setText("Patient.");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lblPatientTitleName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPatientTitleName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientTitleName.setText("Name:");

        lblPatientTitleAddress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPatientTitleAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientTitleAddress.setText("Address:");

        lblPatientTitleSex.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPatientTitleSex.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientTitleSex.setText("Sex:");

        lblPatientTitleAge.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPatientTitleAge.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientTitleAge.setText("Age:");

        lblPatientName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientName.setText("Firstname Surname");

        lblPatientAddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPatientAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientAddress.setText("BuildingName, Road, City, Postcode");

        lblPatientSex.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPatientSex.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientSex.setText("Male/Female");

        lblPatientAge.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPatientAge.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientAge.setText("00");

        lblDoctorTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDoctorTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorTitle.setText("Doctor.");

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        lblDoctorTitleName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDoctorTitleName.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorTitleName.setText("Name:");

        lblDoctorTitleAddress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDoctorTitleAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorTitleAddress.setText("Address:");

        lblDoctorName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblDoctorName.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorName.setText("Firstname Surname");

        lblDoctorAddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblDoctorAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctorAddress.setText("BuildingName, Road, City, Postcode");

        lblNotesTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNotesTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblNotesTitle.setText("Notes:");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        txtaNotes.setEditable(false);
        txtaNotes.setBackground(new java.awt.Color(76, 107, 110));
        txtaNotes.setColumns(20);
        txtaNotes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtaNotes.setForeground(new java.awt.Color(255, 255, 255));
        txtaNotes.setRows(5);
        txtaNotes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jScrollPane2.setViewportView(txtaNotes);

        lblMedicineTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMedicineTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicineTitle.setText("Medicine:");
        lblMedicineTitle.setToolTipText("");

        tblMedicine.setBackground(new java.awt.Color(76, 107, 110));
        tblMedicine.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tblMedicine.setForeground(new java.awt.Color(255, 255, 255));
        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Medicine", "Quantity", "Dosage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedicine.setGridColor(new java.awt.Color(255, 255, 255));
        tblMedicine.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tblMedicine);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblTitle)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPatientTitle)
                                    .addComponent(lblPatientTitleName)
                                    .addComponent(lblPatientTitleAddress)
                                    .addComponent(lblPatientTitleSex)
                                    .addComponent(lblPatientTitleAge))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientName)
                                    .addComponent(lblPatientAddress)
                                    .addComponent(lblPatientSex)
                                    .addComponent(lblPatientAge))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDoctorTitle)
                                    .addComponent(lblDoctorTitleName)
                                    .addComponent(lblDoctorTitleAddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDoctorName)
                                    .addComponent(lblDoctorAddress)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblNotesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedicineTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblDoctorTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctorTitleName)
                            .addComponent(lblDoctorName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctorTitleAddress)
                            .addComponent(lblDoctorAddress))
                        .addGap(60, 60, 60))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblPatientTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientTitleName)
                            .addComponent(lblPatientName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientTitleAddress)
                            .addComponent(lblPatientAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientTitleSex)
                            .addComponent(lblPatientSex))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientTitleAge)
                            .addComponent(lblPatientAge))))
                .addGap(30, 30, 30)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNotesTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicineTitle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perscriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perscriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perscriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perscriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perscriptionUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblDoctorAddress;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblDoctorTitle;
    private javax.swing.JLabel lblDoctorTitleAddress;
    private javax.swing.JLabel lblDoctorTitleName;
    private javax.swing.JLabel lblMedicineTitle;
    private javax.swing.JLabel lblNotesTitle;
    private javax.swing.JLabel lblPatientAddress;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientSex;
    private javax.swing.JLabel lblPatientTitle;
    private javax.swing.JLabel lblPatientTitleAddress;
    private javax.swing.JLabel lblPatientTitleAge;
    private javax.swing.JLabel lblPatientTitleName;
    private javax.swing.JLabel lblPatientTitleSex;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTable tblMedicine;
    private javax.swing.JTextArea txtaNotes;
    // End of variables declaration//GEN-END:variables
}
