/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiview;

/**
 *
 * @author kacper
 */
public class secretaryPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanelUI
     */
    public secretaryPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlManageAccounts = new javax.swing.JPanel();
        lblPatientsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPatients = new javax.swing.JList<>();
        btnRemove = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        pnlAppointments = new javax.swing.JPanel();
        lblPatientsTitle1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAppointments = new javax.swing.JList<>();
        jSeparator8 = new javax.swing.JSeparator();
        btnApproveAppointment = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemoveAppointment = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        pnlMedicine = new javax.swing.JPanel();
        lblGiveMedicineTitle = new javax.swing.JLabel();
        lblSearchPatientTitle = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblListOfMedicineTitle = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstUserMedicine = new javax.swing.JList<>();
        btnOrderMedicine = new javax.swing.JButton();
        btnGiveMedicine = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPatientResults = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        lblRestockMedicineTitle = new javax.swing.JLabel();
        lblMedicineListTitle = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstRestockMedicineList = new javax.swing.JList<>();
        btnRestock = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lblAddCustomTitle = new javax.swing.JLabel();
        lblMedicineNameTitle = new javax.swing.JLabel();
        txtMedicineName = new javax.swing.JTextField();
        lblMedicineQuantityTitle = new javax.swing.JLabel();
        txtMedicineQuantity = new javax.swing.JTextField();
        btnCustomOrder = new javax.swing.JButton();

        setBackground(new java.awt.Color(76, 107, 110));

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        pnlManageAccounts.setBackground(new java.awt.Color(143, 174, 177));

        lblPatientsTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPatientsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientsTitle.setText("Patients:");

        lstPatients.setBackground(new java.awt.Color(255, 255, 255));
        lstPatients.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(lstPatients);

        btnRemove.setBackground(new java.awt.Color(255, 255, 255));
        btnRemove.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(102, 102, 102));
        btnRemove.setText("Remove");

        btnApprove.setBackground(new java.awt.Color(255, 255, 255));
        btnApprove.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(102, 102, 102));
        btnApprove.setText("Approve");

        javax.swing.GroupLayout pnlManageAccountsLayout = new javax.swing.GroupLayout(pnlManageAccounts);
        pnlManageAccounts.setLayout(pnlManageAccountsLayout);
        pnlManageAccountsLayout.setHorizontalGroup(
            pnlManageAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageAccountsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblPatientsTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageAccountsLayout.createSequentialGroup()
                .addGap(0, 121, Short.MAX_VALUE)
                .addGroup(pnlManageAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlManageAccountsLayout.createSequentialGroup()
                        .addComponent(btnRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        pnlManageAccountsLayout.setVerticalGroup(
            pnlManageAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageAccountsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblPatientsTitle)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlManageAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(btnApprove))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ManageAccounts", pnlManageAccounts);

        pnlAppointments.setBackground(new java.awt.Color(143, 174, 177));
        pnlAppointments.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblPatientsTitle1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPatientsTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientsTitle1.setText("Appointments:");

        lstAppointments.setBackground(new java.awt.Color(255, 255, 255));
        lstAppointments.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lstAppointments.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(lstAppointments);

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        btnApproveAppointment.setBackground(new java.awt.Color(255, 255, 255));
        btnApproveAppointment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnApproveAppointment.setForeground(new java.awt.Color(102, 102, 102));
        btnApproveAppointment.setText("Approve Appointmnet");

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(102, 102, 102));
        btnEdit.setText("Edit");

        btnRemoveAppointment.setBackground(new java.awt.Color(255, 255, 255));
        btnRemoveAppointment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRemoveAppointment.setForeground(new java.awt.Color(102, 102, 102));
        btnRemoveAppointment.setText("Remove");

        btnAddNew.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNew.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddNew.setForeground(new java.awt.Color(102, 102, 102));
        btnAddNew.setText("Add New");

        javax.swing.GroupLayout pnlAppointmentsLayout = new javax.swing.GroupLayout(pnlAppointments);
        pnlAppointments.setLayout(pnlAppointmentsLayout);
        pnlAppointmentsLayout.setHorizontalGroup(
            pnlAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAppointmentsLayout.createSequentialGroup()
                .addGroup(pnlAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAppointmentsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddNew))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAppointmentsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAppointmentsLayout.createSequentialGroup()
                                .addComponent(lblPatientsTitle1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlAppointmentsLayout.createSequentialGroup()
                        .addContainerGap(150, Short.MAX_VALUE)
                        .addGroup(pnlAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAppointmentsLayout.createSequentialGroup()
                                .addComponent(btnRemoveAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnApproveAppointment)))))
                .addGap(74, 74, 74))
        );
        pnlAppointmentsLayout.setVerticalGroup(
            pnlAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAppointmentsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblPatientsTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddNew)
                .addGap(15, 15, 15)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pnlAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnApproveAppointment)
                    .addComponent(btnRemoveAppointment))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultations", pnlAppointments);

        pnlMedicine.setBackground(new java.awt.Color(143, 174, 177));

        lblGiveMedicineTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblGiveMedicineTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblGiveMedicineTitle.setText("Give Medicine:");
        lblGiveMedicineTitle.setToolTipText("");

        lblSearchPatientTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSearchPatientTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchPatientTitle.setText("Search Patient:");
        lblSearchPatientTitle.setToolTipText("");

        txtSearchName.setBackground(new java.awt.Color(255, 255, 255));
        txtSearchName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSearchName.setForeground(new java.awt.Color(0, 0, 0));
        txtSearchName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSearch.setText("Search");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblListOfMedicineTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblListOfMedicineTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblListOfMedicineTitle.setText("List Of Medicine:");
        lblListOfMedicineTitle.setToolTipText("");

        lstUserMedicine.setBackground(new java.awt.Color(255, 255, 255));
        lstUserMedicine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lstUserMedicine.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(lstUserMedicine);

        btnOrderMedicine.setBackground(new java.awt.Color(255, 255, 255));
        btnOrderMedicine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnOrderMedicine.setText("Order");

        btnGiveMedicine.setBackground(new java.awt.Color(255, 255, 255));
        btnGiveMedicine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnGiveMedicine.setText("Give");

        lstPatientResults.setBackground(new java.awt.Color(255, 255, 255));
        lstPatientResults.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lstPatientResults.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(lstPatientResults);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lblRestockMedicineTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRestockMedicineTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRestockMedicineTitle.setText("Restock Medicine:");
        lblRestockMedicineTitle.setToolTipText("");

        lblMedicineListTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMedicineListTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicineListTitle.setText("Medicine List:");
        lblMedicineListTitle.setToolTipText("");

        lstRestockMedicineList.setBackground(new java.awt.Color(255, 255, 255));
        lstRestockMedicineList.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lstRestockMedicineList.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane6.setViewportView(lstRestockMedicineList);

        btnRestock.setBackground(new java.awt.Color(255, 255, 255));
        btnRestock.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRestock.setText("Restock");

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAddCustomTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAddCustomTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAddCustomTitle.setText("Add Custom");
        lblAddCustomTitle.setToolTipText("");

        lblMedicineNameTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMedicineNameTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicineNameTitle.setText("Name:");

        txtMedicineName.setBackground(new java.awt.Color(255, 255, 255));
        txtMedicineName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMedicineName.setForeground(new java.awt.Color(0, 0, 0));
        txtMedicineName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblMedicineQuantityTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMedicineQuantityTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicineQuantityTitle.setText("Quantity:");

        txtMedicineQuantity.setBackground(new java.awt.Color(255, 255, 255));
        txtMedicineQuantity.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMedicineQuantity.setForeground(new java.awt.Color(0, 0, 0));
        txtMedicineQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnCustomOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomOrder.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCustomOrder.setText("Custom Order ");

        javax.swing.GroupLayout pnlMedicineLayout = new javax.swing.GroupLayout(pnlMedicine);
        pnlMedicine.setLayout(pnlMedicineLayout);
        pnlMedicineLayout.setHorizontalGroup(
            pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicineLayout.createSequentialGroup()
                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblGiveMedicineTitle))
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMedicineLayout.createSequentialGroup()
                                .addComponent(lblSearchPatientTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListOfMedicineTitle)
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addComponent(btnOrderMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGiveMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
            .addGroup(pnlMedicineLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedicineListTitle)
                            .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRestock, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMedicineLayout.createSequentialGroup()
                                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMedicineQuantityTitle)
                                    .addComponent(lblMedicineNameTitle))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedicineQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCustomOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addComponent(lblRestockMedicineTitle)
                        .addGap(231, 231, 231)
                        .addComponent(lblAddCustomTitle)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlMedicineLayout.setVerticalGroup(
            pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicineLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblGiveMedicineTitle)
                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearchPatientTitle)
                            .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblListOfMedicineTitle))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMedicineLayout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMedicineLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOrderMedicine)
                                    .addComponent(btnGiveMedicine)))))
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestockMedicineTitle)
                    .addComponent(lblAddCustomTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addComponent(lblMedicineListTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestock))
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMedicineLayout.createSequentialGroup()
                                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMedicineNameTitle))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMedicineQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMedicineQuantityTitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCustomOrder))
                            .addComponent(jSeparator3))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Medicine", pnlMedicine);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnApproveAppointment;
    private javax.swing.JButton btnCustomOrder;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGiveMedicine;
    private javax.swing.JButton btnOrderMedicine;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRemoveAppointment;
    private javax.swing.JButton btnRestock;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAddCustomTitle;
    private javax.swing.JLabel lblGiveMedicineTitle;
    private javax.swing.JLabel lblListOfMedicineTitle;
    private javax.swing.JLabel lblMedicineListTitle;
    private javax.swing.JLabel lblMedicineNameTitle;
    private javax.swing.JLabel lblMedicineQuantityTitle;
    private javax.swing.JLabel lblPatientsTitle;
    private javax.swing.JLabel lblPatientsTitle1;
    private javax.swing.JLabel lblRestockMedicineTitle;
    private javax.swing.JLabel lblSearchPatientTitle;
    private javax.swing.JList<String> lstAppointments;
    private javax.swing.JList<String> lstPatientResults;
    private javax.swing.JList<String> lstPatients;
    private javax.swing.JList<String> lstRestockMedicineList;
    private javax.swing.JList<String> lstUserMedicine;
    private javax.swing.JPanel pnlAppointments;
    private javax.swing.JPanel pnlManageAccounts;
    private javax.swing.JPanel pnlMedicine;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtMedicineQuantity;
    private javax.swing.JTextField txtSearchName;
    // End of variables declaration//GEN-END:variables
}
